[package]
name = "flashparser"
version = "0.1.0"
edition = "2021"
authors = ["Junbeom Lee <junbeoml22@gmail.com>"]
description = "A fast and safe numeric parser for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JunbeomL22/flashparser"
keywords = ["parser", "parsing", "numeric-parser", "fast", "safe", "bit-operation"]

[[bench]]
name = "integer"
harness = false

[[bench]]
name = "unsigned"
harness = false


[dependencies]
fast-float = "0.2"
atoi = "2.0"
itoa = "0.4"
criterion = "0.5"
num-traits = "0.2"
anyhow = "1.0"
memchr = "2"