[package]
name = "biscuit-converter"
version = "0.2.0"
edition = "2021"
authors = ["Junbeom Lee <junbeoml22@gmail.com>"]
description = "A fast and safe numeric parser for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JunbeomL22/biscuit-converter"
keywords = ["parser", "numeric-parser", "fast", "safe", "bit-operation"]

[[bench]]
name = "integer"
harness = false

[[bench]]
name = "unsigned"
harness = false

[dependencies]
atoi = "2.0"
criterion = "0.5"
num-traits = "0.2"
anyhow = "1.0"